
const MESSAGE = {
	'CREATE_ROOM': 'CREATE_ROOM',
	'JOIN_ROOM': 'JOIN_ROOM',
	'LEAVE_ROOM': 'LEAVE_ROOM',
	'JOIN_TEAM': 'JOIN_TEAM',
	'USER_LEFT': 'USER_LEFT',
	'START_GAME': 'START_GAME',
	'SUBMIT_STROKE': 'SUBMIT_STROKE',
	'SUBMIT_CARDS': 'SUBMIT_CARDS',
	'NEW_TURN': 'NEW_TURN',
	'TURN_START': 'TURN_START',
	'NEXT_CARD': 'NEXT_CARD',
	'TURN_END': 'TURN_END',
	'SKIP_ROUND': 'SKIP_ROUND',
	'RETURN_TO_SETUP': 'RETURN_TO_SETUP',
};

module.exports = MESSAGE;